services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadbhost:3306/hibernate_spring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mariadb
    hostname: mariadbhost
    expose:
      - "3306"
    environment:
      MARIADB_DATABASE: hibernate_spring
      MARIADB_ROOT_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -p$$MARIADB_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
