services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadbapp:3306/hibernate_spring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    hostname: mariadbapp
    environment:
      MARIADB_DATABASE: hibernate_spring
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
